// <auto-generated />
using MVCProducto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCProducto.Migrations
{
    [DbContext(typeof(ProductosDBContext))]
    partial class ProductosDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCProducto.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Electronica"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ropa"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Alimentos"
                        });
                });

            modelBuilder.Entity("MVCProducto.Models.Producto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CodigoCategoria")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CodigoCategoria");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CodigoCategoria = 1,
                            NombreProducto = "Smartphone",
                            Precio = 299.99m,
                            Stock = 50
                        },
                        new
                        {
                            ID = 2,
                            CodigoCategoria = 2,
                            NombreProducto = "Camisa",
                            Precio = 19.99m,
                            Stock = 200
                        },
                        new
                        {
                            ID = 3,
                            CodigoCategoria = 3,
                            NombreProducto = "Pan",
                            Precio = 1.99m,
                            Stock = 100
                        },
                        new
                        {
                            ID = 5,
                            CodigoCategoria = 1,
                            NombreProducto = "Laptop",
                            Precio = 799.99m,
                            Stock = 30
                        },
                        new
                        {
                            ID = 6,
                            CodigoCategoria = 2,
                            NombreProducto = "Zapatos",
                            Precio = 49.99m,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("MVCProducto.Models.Producto", b =>
                {
                    b.HasOne("MVCProducto.Models.Categoria", "Categoria")
                        .WithMany("Producto")
                        .HasForeignKey("CodigoCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MVCProducto.Models.Categoria", b =>
                {
                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
